### PR TITLE
Context reorginizations

### PR DESCRIPTION
**Pull request by dannylamb**
**GitHub Issue**: Resolves https://github.com/Islandora/documentation/issues/1313

# What does this Pull Request do?

Functionally nothing.  It just reorganizes the Context page with 'Indexing', 'Derivative', and 'Display' groups.

# How should this be tested?

- Pull down this PR
- `drush fim -y islandora_defaults`
- Visit localhost:8000/admin/context, you should see this:
image

# Interested parties
@DonRichards @Islandora/8-x-committers

### CODE REVIEW

**Comment by mjordan** [comment]
@dannylamb works as advertised. Question: If an admin adds their own context, is it possible to put it under one of those groupings? And if so, how would one do that?

**Comment by dannylamb** [comment]
You can change the group for a context on its edit form.  It's a tags style field, so you can just make one up if you want, too.  Reordering on the main page only seems to reorder within groups, but you can't drag and drop one between goups :(

**Comment by mjordan** [comment]
Woops, spoke too soon, there's an anomaly in the left warp nacelle: the group says "Indexing" in all cases:

context_groups

**Comment by dannylamb** [comment]
@mjordan I cleared my cache after importing the feature on a new box and everything worked as expected.  We're picking up a new context from islandora_fits that's not getting assinged to one of the three groups, though. Ideally it'd come over to this repo.  But for now, this PR covers all the contexts in this repo.

**Comment by mjordan** [comment]
OK, drush cr worked its magick. I also added a new context and a new group, and moved one of the Islandora contexts into this new group. All is well.

**Comment by dannylamb** [comment]
@mjordan Nope, for me the Islandora FITS context was in the Islandora group.  We're experiencing the same thing.  If you're good, I'm good.

**Pull request merged**
