### PR TITLE
Add 'Original Name' field to Media

### PR DESCRIPTION
**Pull request by seth-shaw-unlv**
**GitHub Issue**: https://github.com/Islandora/documentation/issues/1276

# What does this Pull Request do?

Adds an 'Original Name' field to Media.

# What's new?

* Added a pile of configs to add the 'Original Name' field, plus their PREMIS 3 mappings.
* Does this change require documentation to be updated? No.
* Does this change add any new dependencies? No.
* Does this change require any other modifications to be made to the repository
 (i.e. Regeneration activity, etc.)? No.
* Could this change impact execution of existing code? No.

# How should this be tested?

Test with https://github.com/Islandora/islandora/pull/735

# Interested parties
@mjordan, @Islandora/8-x-committers

### CODE REVIEW

**Comment by mjordan** [comment]
I can test this, but not until the weekend.

**Comment by mjordan** [comment]
@Islandora/8-x-committers anyone know why travis stalled?

**Comment by seth-shaw-unlv** [comment]
Travis says this is not an active repository. This is an issue for @dannylamb, I believe.

**Comment by manez** [comment]
Is it because [this](https://github.com/Islandora/islandora_defaults/blob/8.x-1.x/.travis.yml) has not been deCLAWed yet?

**Comment by dannylamb** [comment]
PR 13 does not exist according to https://travis-ci.com/Islandora/islandora_defaults/pull_requests :man_shrugging:  Try poking Travis with a white space commit and see if he responds. Everything's set up and _should_:tm: function fine as-is due to redirects (de-CLAWing would still be preferable tho).

**Comment by mjordan** [comment]
Even though travis says "66.2 | 7.3 | errored | This job is allowed to fail." I can't merge because of the failed build.

**Comment by mjordan** [comment]
@seth-shaw-unlv OK, I just merged https://github.com/Islandora/islandora/pull/735.

**Comment by seth-shaw-unlv** [comment]
Travis builds are restarted.

**Comment by mjordan** [comment]
Hm, still failing.

**Comment by seth-shaw-unlv** [comment]
Hey! Looks like this isn't my fault. [Packagist](https://packagist.org/packages/islandora/islandora#dev-8.x-1.x) is still pointing composer at Islandora-CLAW/islandora. (See the 'Source' link on the packagist page.) I don't know who needs to make that change, although @dannylamb  and @DiegoPino are both listed on the packagist page.

Once that is fixed this should work fine. I just need to revert my travis changes. I'll do that after the Packagist references are fixed.

**Comment by mjordan** [comment]
Cool, ping me when everything is ready and I'll merge.

**Comment by dannylamb** [comment]
@seth-shaw-unlv I hit the update button again on packagist and now the source page leads to Islandora/islandora.  I'm restarting the build on Travis to see if gets picked up.

**Comment by seth-shaw-unlv** [comment]
@dannylamb, now https://packagist.org/packages/islandora/islandora#dev-8.x-1.x has a source value of the 7.x branch (https://github.com/Islandora/islandora/tree/7.x).

**Comment by dannylamb** [comment]
@seth-shaw-unlv Just had to jiggle the cable on it.  You're good to go now.

**Comment by mjordan** [comment]
Tested with https://github.com/Islandora/islandora/pull/735, works as described.

**Pull request merged**
