### PR TITLE
Fixing facets that are breaking search

### PR DESCRIPTION
**Pull request by dannylamb**
**GitHub Issue**: Follow up to https://github.com/Islandora/islandora_defaults/pull/52

Blocking https://github.com/Islandora/islandora/pull/843

# What does this Pull Request do?

Points facets towards the correct fields on the solr index after the MIG sandbox changes. The facets are currently pointing at fields that are no longer in the index, and it's making search fail silently.

# What's new?

* Touching up the solr index fields
* Pointing facets towards those fields instead of nonexistant ones
* Deleted vocabs here that already are / should be in controlled_access_terms_defaults.

# How should this be tested?

Original Behaviour:

Try to search, you'll get no results and no real indication that anything went wrong.

## How to get an environment to test this

I used ISLE. Make sure you have the latest `isle-dc`, and from within its directory

1. `sudo rm -rf codebase; git clone https://github.com/islandora-devops/islandora-sandbox codebase`
2. Set `ENVIRONMENT=local` in your .env (rename `sample.env` to `.env` if you don't have it)
3. Set `TAG=1.0.0-alpha-9`
3. `make local`
4. Pull ths PR into `codebase/web/modules/contrib/islandora_defaults`
5. Pull https://github.com/Islandora/controlled_access_terms/pull/71 into `codebase/web/modules/contrib/controlled_access_terms`
6. `docker-compose exec drupal with-contenv bash -lc 'drush -y en facets name islandora_search'`
9. `docker-compose exec drupal with-contenv bash -lc 'drush -y fim controlled_access_terms_defaults'`
10. `docker-compose exec drupal with-contenv bash -lc 'drush -y fim islandora_defaults'`
11. `docker-compose exec drupal with-contenv bash -lc 'drush -y fim islandora_search'` (it will complain about not being able to reach the solr server.  that's fine.  the next step fixes it)
12. `make hydrate`

Then you can go add some terms, make some content, and try to search it.  Search should work and you should see facets.

image

# Interested parties

@Islandora/8-x-committers

### CODE REVIEW

**Comment by seth-shaw-unlv** [comment]
@dannylamb, because of https://github.com/Islandora/controlled_access_terms/pull/70 we need to pull php 7.3 from the testing matrix, e.g. https://github.com/Islandora/controlled_access_terms/commit/e6aec2795480453b7b55e46052145be7df74a5e6#diff-3ed6605c09cf098b9fca42efddf606e06d3a52480a19969687a97471d06490cbL24

**Comment by dannylamb** [comment]
I can do that @seth-shaw-unlv

**Comment by dannylamb** [comment]
:fire: :fire: :fire:

**Comment by dannylamb** [comment]
There's a corresponding pull to controlled_access_terms I need to issue as well before this goes in.

**Comment by dannylamb** [comment]
Oh ha, right... `facets` is an optional dependency.... hang on

**Comment by dannylamb** [comment]
Currently spinning up a fresh ISLE to make sure this installs correctly from scratch.  I'll update testing instructions with what I did... assuming everything goes ok.

**Comment by dannylamb** [comment]
Bah, now it's complaining about the `temporal_subjects` vocabulary, which I moved over to `controlled_access_terms`. I'll have to sort that out. :sob:

**Comment by dannylamb** [comment]
This will fail until https://github.com/Islandora/controlled_access_terms/pull/71 is merged

**Comment by dannylamb** [comment]
@seth-shaw-unlv or any other @Islandora/8-x-committers :arrow_right: :mega:  I've updated testing instructions, and this fixes searching. Please help me get this and https://github.com/Islandora/controlled_access_terms/pull/71 in so I can merge https://github.com/Islandora/islandora/pull/843 and finish the release. :pray: :pray: :pray:

**Review by seth-shaw-unlv — APPROVED** [review]
🚀

**Pull request merged**
