### PR TITLE
Remove access_terms

### PR DESCRIPTION
**Pull request by rosiel**
**Slack discussion**: https://islandora.slack.com/archives/C019U12D44Q/p1643905893529709

# What does this Pull Request do?

Solves the unmet dependencies preventing mirador from being installed.

# What's new?

* removed references to a field (that was "hidden" anyway)

# How should this be tested?

Currently when trying to install islandora defaults, it doesn't let you install Islandora_mirador. 
however with this, it can be installed

# Additional Notes:
Any additional information that you think would be helpful when reviewing this
 PR.

# Interested parties
@ajstanley

### CODE REVIEW

**Review by ajstanley — COMMENTED** [review]
Tested - work perfectly.

**Review by ajstanley — APPROVED** [review]

**Comment by rosiel** [comment]
@ajstanley the build is green now... :)

**Comment by rosiel** [comment]
@whikloj do you still want to review this? I can push the branch to islandora if that helps (according to what I know which is documented [here](https://docs.lefaive.ca/w/index.php/Testing_Pull_Requests#Example%3A_Pulling_in_a_PR_branch_for_Islandora_Defaults_with_the_Playbook), its' very difficult to test an islandora defaults that's not a branch of the main repo)

**Comment by rosiel** [comment]
@whikloj in case it helps make testing easier, i've pushed this to a branch on Islandora: https://github.com/Islandora/islandora_defaults/tree/mirador-2

**Comment by whikloj** [comment]
Sorry @rosiel, I'm spinning up a new islandora-playbook now.

**Pull request merged**
