### PR TITLE
Fix reference to issue branch in composer

### PR DESCRIPTION
**Pull request by seth-shaw-unlv**
Reverts Islandora/islandora_defaults#36

Reverts the change to composer.json

@mjordan, we needed to take out this composer change before merging.

### CODE REVIEW

**Review by rosiel — COMMENTED** [review]
so... we had to change this to your issue branch for the build to work, and now we change it back? If that's the case, i approve?

**Comment by seth-shaw-unlv** [comment]
@rosiel, exactly. We added this so we could test a fresh build of the controlled access terms PR. Now that it is ready to merge we need to change it back.

**Comment by mjordan** [comment]
I can review/test this afternoon.

**Comment by seth-shaw-unlv** [comment]
There is nothing to test here. We are simply pointing composer back to the dev branch *instead of* the PR branch.

**Comment by mjordan** [comment]
@seth-shaw-unlv sorry, was responding in in-meeting-mode. Approving and merging now.

**Review by mjordan — APPROVED** [review]
Approved for reasons explained in comments.

**Pull request merged**
