### PR TITLE
Issue 1369: Drop Comments Dependency

### PR DESCRIPTION
**Pull request by seth-shaw-unlv**
**GitHub Issue**: https://github.com/Islandora/documentation/issues/1369

# What does this Pull Request do?

The comment module was hanging on as a dependency despite not being necessary. This PR adjusts the configs so we can finally be free of the dependency.

# What's new?

* Replaces the search_api and search_api_solr_defaults with search_api_solr.
* Moves the solr server and index configs from `/config/optional/` to `/config/install/`  
* Removed comment module dependency

# How should this be tested?

* View the Uninstall page any existing Islandora box and the Comment module will list several islandora-related dependencies.
* Clone the islandora-playbook
* Change [`inventory/vagrant/group_vars/webserver/drupal.yml` line 22](https://github.com/Islandora-Devops/islandora-playbook/blob/dev/inventory/vagrant/group_vars/webserver/drupal.yml#L22) from `  - "islandora/islandora_defaults:dev-8.x-1.x"` (or whatever islandora_defaults branch it targets) to `  - "islandora/islandora_defaults:dev-issue-1369"`.
* *Change the base box* E.g. `set ISLANDORA_DISTRO='ubuntu/bionic64'` OR `set ISLANDORA_DISTRO='centos/7'`.
* `vagrant up --provision` and wait.....
* Once it is up check the Uninstall page for the Comment module. *It will still not allow you to uninstall it (there is a dependency on the Article content type that Drupal installed) but at least all the islandora dependencies are gone now.*

# Additional Notes:
As mentioned in the testing instructions, this will not rid us of the Comment module; but it does make it easier. Just delete the comments field from the Article content type and you are good to go.

# Interested parties
@mjordan

### CODE REVIEW

**Comment by mjordan** [comment]
@seth-shaw-unlv I needed to change to the playbook's `dev` branch to avoid the Drupal Console problem, and I think that may have tainted the environment since I'm still seeing the Islandora dependencies. Here is the Comment entry from the uninstall page in an existing playbook:

comment_before

Here is the Comment entry from the uninstall page in my test environment with the drupal.yml's line 22 being `"islandora/islandora_defaults:dev-issue-1369"`:

comment_after

Do you think building in the `dev` branch would interfere with your changes?

**Comment by seth-shaw-unlv** [comment]
@mjordan, I also switched to the dev branch before updating that line.... so it *should* have worked. Was it a fresh playbook, or did you run it on a box that had already been provisioned before?

OH! Did you change the base-box? You either need to build from ubuntu or centos, not use the pre-built box. I should have mentioned that in the testing instructions. 🤦‍♂️ *I've now updated the testing instructions.*

**Comment by mjordan** [comment]
Fresh. I destroyed between attempts.

**Comment by mjordan** [comment]
Sorry, I did not change the base box. Lemme try that.

**Comment by mjordan** [comment]
Nice, that worked:

comments

But I'd like to continue testing to see what the effect of disabling `search_api_solr_defaults` is so I can then nuke `comment`. Will report back here.

**Comment by mjordan** [comment]
Welp, `search_api_solr_defaults.info.yml` tells me what the effect of disabling it is:

> Enable this module for a best-practice default setup of Search API with the Solr backend. After installation it is recommended to uninstall this module again for performance reasons. The provided configuration will not be removed.

So, we're good to go! Should I wait to merge this ~~and `islandora/islandora_defaults:dev-issue-1369` at the same time~~?

**Comment by seth-shaw-unlv** [comment]
Oh, we need to update [the playbook](https://github.com/Islandora-Devops/islandora-playbook/blob/main/inventory/vagrant/group_vars/webserver/drupal.yml#L46) to get rid of it. I did that during testing and it worked fine, but that would be a separate PR.

**Comment by mjordan** [comment]
Want me to do that or do you want to?

**Comment by seth-shaw-unlv** [comment]
I can do it. Just a moment.

**Comment by seth-shaw-unlv** [comment]
Accidentally created a PR against my own fork instead of the Islandora-Devops repo. 🤦‍♂️

@mjordan, it would be best to merge this PR first and then the playbook one.

**Comment by mjordan** [comment]
OK, I'll test building a box from https://github.com/Islandora-Devops/islandora-playbook/pull/187 tomorrow and if all goes well, merge this PR and then that one.

Thanks!

**Comment by mjordan** [comment]
Build successful, with dependencies resolved:

comments

**Review by mjordan — APPROVED** [review]
Tested and working as intended.

**Pull request merged**
