### PR TITLE
Delete context.context.files_in_fedora.yml

### PR DESCRIPTION
**Pull request by dannylamb**
**GitHub Issue**: Part of this mess: https://github.com/Islandora-Devops/isle-dc/pull/132

# What does this Pull Request do?

Deletes a context we no longer need b/c we don't use Gemini anymore.

# What's new?
One less context.  It wasn't hurting anything just laying around, but I'm trying to be tidy here.

Does this warrant an update hook to delete it from existing sites?  Or should I just add instructions to do it in the release notes? @Islandora/8-x-committers ?

### CODE REVIEW

**Comment by seth-shaw-unlv** [comment]
Should we also then get rid of the corresponding actions in islandora_core_feature? 

- https://github.com/Islandora/islandora/blob/8.x-1.x/modules/islandora_core_feature/config/install/system.action.index_file_in_fedora.yml
- https://github.com/Islandora/islandora/blob/8.x-1.x/modules/islandora_core_feature/config/install/system.action.delete_file_from_fedora.yml

**Comment by dannylamb** [comment]
Sounds prudent to me

**Comment by dannylamb** [comment]
Linking this to https://github.com/Islandora/documentation/issues/1848 since that's how I discovered that this needs to be deleted.

**Comment by dannylamb** [comment]
@Islandora/8-x-committers Bumpin' this for the release.

@seth-shaw-unlv is out on :palm_tree: , so I need someone else to step up and get this in.

**Review by elizoller — APPROVED** [review]
i pulled in this PR, verified the context was deleted. tested adding an item with an original file and verified that the original file still made it to fedora. seems good.

**Comment by dannylamb** [comment]
can haz merge?

**Pull request merged**
