### PR TITLE
redirect not working

### PR DESCRIPTION
**Pull request by DonRichards**
**GitHub Issue**: n/a

# What does this Pull Request do?
Fix URL

# What's new?
N/A

# How should this be tested?
Check URL

# Additional Notes:
N/A

# Interested parties
@Islandora/8-x-committers

### CODE REVIEW

**Review by manez — APPROVED** [review]
Someday, we'll well and truly see the last of these. Someday....

**Review by seth-shaw-unlv — APPROVED** [review]
👍

**Comment by seth-shaw-unlv** [comment]
We can merge once green.

**Comment by seth-shaw-unlv** [comment]
Travis is actually green even though it isn't reporting accurately here. Merging.

**Pull request merged**
